# Generated by Django 3.2.12 on 2022-03-21 13:31

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_text_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Address Text Table',
            },
        ),
        migrations.CreateModel(
            name='bennar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploads/product_image')),
            ],
            options={
                'verbose_name_plural': 'Bennar',
            },
        ),
        migrations.CreateModel(
            name='blog_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('discription', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Blog_video', models.FileField(blank=True, default=None, null=True, upload_to='Blog_video')),
                ('img', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img6', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 19, 31, 17, 518015))),
            ],
            options={
                'verbose_name_plural': 'Blog Post',
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_name', models.CharField(max_length=255)),
                ('Brand_discription', models.TextField(default='')),
                ('Brand_image', models.ImageField(blank=True, default='', null=True, upload_to='uploads/category_img')),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('catalog_url', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'catalog',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_discription', models.TextField()),
                ('Category_image', models.ImageField(blank=True, default='', null=True, upload_to='uploads/category_img')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='contact_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact Table',
            },
        ),
        migrations.CreateModel(
            name='Custom_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Company_Name', models.CharField(max_length=255)),
                ('Email_Adress', models.CharField(max_length=255)),
                ('Phone_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('Project_Name', models.CharField(max_length=255)),
                ('Details', models.TextField(blank=True, null=True)),
                ('Attach_File', models.FileField(blank=True, null=True, upload_to='custom_project/attach/')),
            ],
            options={
                'verbose_name_plural': 'Custom Project',
            },
        ),
        migrations.CreateModel(
            name='Discount_Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('discount_percentage', models.IntegerField(default='0')),
                ('active_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Discount Coupon',
            },
        ),
        migrations.CreateModel(
            name='dynamic_theme_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=255)),
                ('color_code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Dynamic Theme Color',
            },
        ),
        migrations.CreateModel(
            name='Navbar_logo_text_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Navbar Logo Text Table',
            },
        ),
        migrations.CreateModel(
            name='newsletter_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=255)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 19, 31, 17, 520010))),
            ],
            options={
                'verbose_name_plural': 'Newsletter Table',
            },
        ),
        migrations.CreateModel(
            name='Number_Table_Navbar_Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Number Table Navbar Footer',
            },
        ),
        migrations.CreateModel(
            name='Product_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('Short_description', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='uploads/product_image')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='uploads/product_image')),
                ('image3', models.ImageField(blank=True, default='', null=True, upload_to='uploads/product_image')),
                ('image4', models.ImageField(blank=True, default='', null=True, upload_to='uploads/product_image')),
                ('image5', models.ImageField(blank=True, default='', null=True, upload_to='uploads/product_image')),
                ('product_status', models.CharField(choices=[('New', 'New'), ('In stock', 'In stock'), ('Out stock', 'Out stock')], default='New', max_length=255)),
                ('catalogue', models.FileField(blank=True, default='', null=True, upload_to='uploads/catalogue')),
                ('datasheets', models.FileField(blank=True, default='', null=True, upload_to='uploads/datasheets')),
                ('Brands', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.brands')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.categories')),
            ],
            options={
                'verbose_name_plural': 'Product Table',
            },
        ),
        migrations.CreateModel(
            name='Service_Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banner_name', models.CharField(max_length=255)),
                ('Service_image', models.ImageField(blank=True, default='', null=True, upload_to='uploads/service_banner')),
            ],
            options={
                'verbose_name_plural': 'Service Banner',
            },
        ),
        migrations.CreateModel(
            name='Service_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_name', models.CharField(max_length=255)),
                ('Service_discription', models.TextField(default='')),
                ('Service_image', models.ImageField(blank=True, default='', null=True, upload_to='uploads/category_img')),
            ],
            options={
                'verbose_name_plural': 'Service Table',
            },
        ),
        migrations.CreateModel(
            name='Social_Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Website', models.CharField(default='', max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Social Links',
            },
        ),
        migrations.CreateModel(
            name='Table_Special_Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Offer_Name', models.CharField(max_length=255)),
                ('Offer_Text', models.TextField(blank=True, default='', null=True)),
                ('offer_image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('offer_expiry_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Special Offer',
            },
        ),
        migrations.CreateModel(
            name='Table_Special_Offer_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Percentage', models.IntegerField()),
                ('Offer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.table_special_offer')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.product_details')),
            ],
            options={
                'verbose_name_plural': 'Special Offer Products',
            },
        ),
        migrations.CreateModel(
            name='Table_Special_Offer_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Percentage', models.IntegerField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.categories')),
                ('Offer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.table_special_offer')),
            ],
            options={
                'verbose_name_plural': 'Special Offer Categories',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subcategory', models.CharField(max_length=255)),
                ('Subcategory_discription', models.TextField()),
                ('Subcategory_image', models.ImageField(blank=True, default='', null=True, upload_to='uploads/Subcategory_img')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.categories')),
            ],
            options={
                'verbose_name_plural': 'Subcategory',
            },
        ),
        migrations.CreateModel(
            name='Service_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('Discription', models.TextField(blank=True, null=True)),
                ('Attachment_files', models.FileField(blank=True, null=True, upload_to='services_picture')),
                ('date', models.DateField(blank=True, default=datetime.datetime(2022, 3, 21, 19, 31, 17, 513029))),
                ('Service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.service_table')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Service Request',
            },
        ),
        migrations.AddField(
            model_name='product_details',
            name='subcategory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.subcategory'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('items_json', models.TextField()),
                ('full_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('full_address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('order_date', models.DateField(blank=True, default=datetime.datetime(2022, 3, 21, 19, 31, 17, 517018))),
                ('Discount_Coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.discount_coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'All Orders',
            },
        ),
        migrations.CreateModel(
            name='EmailConfirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=255)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Email-Confirmed',
            },
        ),
        migrations.CreateModel(
            name='Blogs_Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_subject', models.CharField(max_length=255)),
                ('comment_text', models.TextField()),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 19, 31, 17, 519013))),
                ('Blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.blog_post')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blogs Comments',
            },
        ),
    ]
