# Generated by Django 3.2.12 on 2022-03-21 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicifyapp', '0002_auto_20220321_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 19, 31, 37, 577154)),
        ),
        migrations.AlterField(
            model_name='blogs_comments',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 19, 31, 37, 578151)),
        ),
        migrations.AlterField(
            model_name='newsletter_table',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 19, 31, 37, 580148)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 3, 21, 19, 31, 37, 576156)),
        ),
        migrations.AlterField(
            model_name='service_request',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 3, 21, 19, 31, 37, 573165)),
        ),
    ]
